name: spidev
description: Dart package for accessing SPI on Linux using the spidev interface.
version: 0.0.1
author: Hannes Winkler
homepage: https://ardera.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8
  tuple: ^1.0.3
  path: ^1.7.0